name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-ocaml:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.14.0
        
    - name: Install dependencies
      run: |
        opam switch import opam.export
        
    - name: Build OCaml project
      run: |
        eval $(opam env)
        dune build src/internal_trace_consumer.exe
        
    - name: Test OCaml project
      run: |
        eval $(opam env)
        dune runtest || echo "No tests found"

  build-rust:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
        
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          internal-log-fetcher/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build Rust project
      working-directory: internal-log-fetcher
      run: cargo build --verbose
      
    - name: Run Rust tests
      working-directory: internal-log-fetcher
      run: cargo test --verbose
      
    - name: Run clippy
      working-directory: internal-log-fetcher
      run: cargo clippy -- -D warnings
      
    - name: Check formatting
      working-directory: internal-log-fetcher
      run: cargo fmt -- --check

  build-docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build . -t internal-trace-consumer:latest